In [1]:
import json
import requests
import re
import pandas as pd 
import numpy as np
import os

In [2]:
path_to_json = '../data-new/fake_insta_accounts'
json_files = [pos_json for pos_json in os.listdir(path_to_json) if pos_json.endswith('.json')]
# print(json_files)

In [3]:
df = pd.DataFrame(json_files)

In [4]:
df.head()

          0
0  683.json
1  379.json
2  396.json
3  115.json
4  545.json

In [5]:
#extracting user names from fake users folder json files
fake_users = []
for js in json_files:
    with open(os.path.join(path_to_json, js)) as json_file:
        json_text = json.load(json_file)
        user_name = json_text["graphql"]["user"]["username"]
        fake_users.append(user_name)

In [6]:
#transform data to data frame
# real_accounts = pd.DataFrame(columns=["user_name", "fullname", "bio", "follower_count", "followers_count", "posts", "reels", "external_url", "privacy",
#                                                 "verification","account_type", "account_category", "profile_pic", "videos", "has_channel", "total_likes"])

In [7]:
L = []

with open("../data-new/real_insta_accounts.json", encoding="utf-8") as json_file:
    json_text = json.load(json_file)
    for x in json_text:
        d = {}
        for k, v in x.items():
            if k == 'latestPosts':
                list = []
                for index,y in enumerate(v):
                    list.append(v[index]['likesCount'])
                index +=1
                d["likes_"] = list
            else:
                d[k] = v
        L.append(d)

In [8]:
real_extract = pd.DataFrame(L)

In [9]:
real_extract.head()

,id,username,url,fullName,biography,externalUrl,externalUrlShimmed,followersCount,followsCount,hasChannel,...,private,verified,profilePicUrl,profilePicUrlHD,facebookPage,igtvVideoCount,relatedProfiles,latestIgtvVideos,postsCount,likes_
0,2266500396,lady__jossy,https://www.instagram.com/lady__jossy,Amponsah Amponsah Baah,Data Scientist \nWild honey üçØ \nWild flower üå∫ ...,None,None,772.0,500.0,False,...,False,False,https://scontent-cdg2-1.cdninstagram.com/v/t51...,https://scontent-cdg2-1.cdninstagram.com/v/t51...,NaN,1.0,[],"[{'type': 'Video', 'shortCode': 'CftQGccKSlx',...",18.0,"[12, 24, 19, 9, 39, 110, 91, 95, 90, 39, 56, 81]"
1,21942638260,ama_afrak,https://www.instagram.com/ama_afrak,Gladys Ama KonaduüáÆüáπüá¨üá≠üá≥üá±üá¨üáß,The Jesus Kind of Girl\nEducationist @gsconsul...,None,None,1010.0,3020.0,False,...,False,False,https://instagram.fhph3-1.fna.fbcdn.net/v/t51....,https://instagram.fhph3-1.fna.fbcdn.net/v/t51....,NaN,0.0,[],[],16.0,"[180, 231, 254, 80, 101, 68, 73, 68, 65, 38, 5..."
2,26756207406,liz.naya,https://www.instagram.com/liz.naya,Liz Wilson Amoofia,Kindly follow my Business page @accesorize_gh\...,None,None,672.0,536.0,False,...,False,False,https://instagram.fala4-1.fna.fbcdn.net/v/t51....,https://instagram.fala4-1.fna.fbcdn.net/v/t51....,NaN,7.0,[],"[{'type': 'Video', 'shortCode': 'CbXAaiCAOIm',...",463.0,"[39, 58, 45, 40, 91, 63, 40, 71, 37, 76, 69, 57]"
3,5551105158,12th._street,https://www.instagram.com/12th._street,Gabriel Engmann,Pharm D\nMPSGH\nBeat Producer\nLink up:12thstr...,None,None,303.0,408.0,False,...,False,False,https://scontent-lcy1-1.cdninstagram.com/v/t51...,https://scontent-lcy1-1.cdninstagram.com/v/t51...,NaN,0.0,[],[],4.0,"[7, 24, 5, 6]"
4,422653739,nii_mantse__,https://www.instagram.com/nii_mantse__,Nii Tetteh,#KingdomCitizen\nGraphic Designer/Video Editor...,None,None,913.0,802.0,False,...,False,False,https://instagram.flba3-2.fna.fbcdn.net/v/t51....,https://instagram.flba3-2.fna.fbcdn.net/v/t51....,NaN,0.0,[],[],7.0,"[43, 156, 179, 31, 143, 175, 81]"

In [10]:
real_extract["med_likes"] = real_extract["likes_"].apply(np.median)

/Users/josephineamponsah/Documents/projects/bot-detector/spammer-detection/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,

In [11]:
real_extract.head(2)

,id,username,url,fullName,biography,externalUrl,externalUrlShimmed,followersCount,followsCount,hasChannel,...,verified,profilePicUrl,profilePicUrlHD,facebookPage,igtvVideoCount,relatedProfiles,latestIgtvVideos,postsCount,likes_,med_likes
0,2266500396,lady__jossy,https://www.instagram.com/lady__jossy,Amponsah Amponsah Baah,Data Scientist \nWild honey üçØ \nWild flower üå∫ ...,None,None,772.0,500.0,False,...,False,https://scontent-cdg2-1.cdninstagram.com/v/t51...,https://scontent-cdg2-1.cdninstagram.com/v/t51...,NaN,1.0,[],"[{'type': 'Video', 'shortCode': 'CftQGccKSlx',...",18.0,"[12, 24, 19, 9, 39, 110, 91, 95, 90, 39, 56, 81]",47.5
1,21942638260,ama_afrak,https://www.instagram.com/ama_afrak,Gladys Ama KonaduüáÆüáπüá¨üá≠üá≥üá±üá¨üáß,The Jesus Kind of Girl\nEducationist @gsconsul...,None,None,1010.0,3020.0,False,...,False,https://instagram.fhph3-1.fna.fbcdn.net/v/t51....,https://instagram.fhph3-1.fna.fbcdn.net/v/t51....,NaN,0.0,[],[],16.0,"[180, 231, 254, 80, 101, 68, 73, 68, 65, 38, 5...",70.5

In [12]:
real_extract.columns

Index(['id', 'username', 'url', 'fullName', 'biography', 'externalUrl',
       'externalUrlShimmed', 'followersCount', 'followsCount', 'hasChannel',
       'highlightReelCount', 'isBusinessAccount', 'joinedRecently',
       'businessCategoryName', 'private', 'verified', 'profilePicUrl',
       'profilePicUrlHD', 'facebookPage', 'igtvVideoCount', 'relatedProfiles',
       'latestIgtvVideos', 'postsCount', 'likes_', 'med_likes'],
      dtype='object')

In [13]:
real_data = real_extract.drop(["id", "url", "externalUrlShimmed","profilePicUrlHD","igtvVideoCount", "latestIgtvVideos", "facebookPage", "relatedProfiles", "likes_"], axis = 1)

In [14]:
real_data["status"] = 1

In [15]:
fakes = []

with open("../data-new/fakes_data.json", encoding="utf-8") as json_file:
    json_text = json.load(json_file)
    for x in json_text:
        dict = {}
        for k, v in x.items():
            if k == 'latestPosts':
                list = []
                for index,y in enumerate(v):
                    list.append(v[index]['likesCount'])
                index +=1
                dict["likes_"] = list
            else:
                dict[k] = v
        fakes.append(dict)

In [16]:
fake_extract = pd.DataFrame(fakes)

In [17]:
fake_extract.head(5)

,id,username,url,fullName,biography,externalUrl,externalUrlShimmed,followersCount,followsCount,hasChannel,...,private,verified,profilePicUrl,profilePicUrlHD,facebookPage,igtvVideoCount,relatedProfiles,latestIgtvVideos,postsCount,likes_
0,44950753876,5x_77886,https://www.instagram.com/5x_77886,ŸÖÿ±ŸäŸàŸÖŸá‚ô•Ô∏è,‚Äè‚ÄÆm_argatsniyab ‚Ä¨‚Äè‚Ä™‚ô´: ùë∫ùë∂ùë∫üîó. \n‚ô´: 16: ùíÄ.ùë∂üêÜ. \n‚ô´...,None,None,87.0,4122.0,False,...,False,False,https://instagram.flhr4-3.fna.fbcdn.net/v/t51....,https://instagram.flhr4-3.fna.fbcdn.net/v/t51....,NaN,0.0,[],[],4.0,"[8, 7, 6, 9]"
1,None,Restricted profile,https://www.instagram.com/mhr._.daad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44852214403,alipoco200,https://www.instagram.com/alipoco200,,,None,None,85.0,6812.0,False,...,False,False,https://scontent-iad3-1.cdninstagram.com/v/t51...,https://scontent-iad3-1.cdninstagram.com/v/t51...,NaN,0.0,[],[],5.0,"[2, 1, 0, 0, 0]"
3,44600232873,maria.saberii7,https://www.instagram.com/maria.saberii7,,,None,None,71.0,5925.0,False,...,True,False,https://instagram.flpb2-2.fna.fbcdn.net/v/t51....,https://instagram.flpb2-2.fna.fbcdn.net/v/t51....,NaN,0.0,[],[],23.0,[]
4,45369596290,athena.____.a,https://www.instagram.com/athena.____.a,,,None,None,138.0,5908.0,False,...,False,False,https://scontent-man2-1.cdninstagram.com/v/t51...,https://scontent-man2-1.cdninstagram.com/v/t51...,NaN,0.0,[],[],4.0,"[55, 49, 60, 54]"

In [18]:
fake_extract.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    333 non-null    object
 1   username              344 non-null    object
 2   url                   344 non-null    object
 3   fullName              333 non-null    object
 4   biography             333 non-null    object
 5   externalUrl           4 non-null      object
 6   externalUrlShimmed    4 non-null      object
 7   followersCount        333 non-null    float64
 8   followsCount          333 non-null    float64
 9   hasChannel            333 non-null    object
 10  highlightReelCount    333 non-null    float64
 11  isBusinessAccount     333 non-null    object
 12  joinedRecently        333 non-null    object
 13  businessCategoryName  12 non-null     object
 14  private               333 non-null    object
 15  verified              333 non-null    object
 16  profilePicUrl         333 non-null    object
 17  profilePicUrlHD       333 non-null    object
 18  facebookPage          0 non-null      float64
 19  igtvVideoCount        333 non-null    float64
 20  relatedProfiles       333 non-null    object
 21  latestIgtvVideos      333 non-null    object
 22  postsCount            333 non-null    float64
 23  likes_                333 non-null    object
dtypes: float64(6), object(18)
memory usage: 64.6+ KB

In [35]:
fake_extract.columns

Index(['id', 'username', 'url', 'fullName', 'biography', 'externalUrl',
       'externalUrlShimmed', 'followersCount', 'followsCount', 'hasChannel',
       'highlightReelCount', 'isBusinessAccount', 'joinedRecently',
       'businessCategoryName', 'private', 'verified', 'profilePicUrl',
       'profilePicUrlHD', 'facebookPage', 'igtvVideoCount', 'relatedProfiles',
       'latestIgtvVideos', 'postsCount', 'likes_', 'med_likes'],
      dtype='object')

In [19]:
fake_extract['likes_'] = fake_extract['likes_'].dropna()

In [20]:
fake_extract["med_likes"] = fake_extract["likes_"].apply(np.median)
# fake_extract["max_likes"] = fake_extract["likes_"].apply(max)
# fake_extract["min_likes"] = fake_extract["likes_"].apply(min)

/Users/josephineamponsah/Documents/projects/bot-detector/spammer-detection/.venv/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,

In [21]:
fake_data = fake_extract.drop(["id", "url", "externalUrlShimmed","profilePicUrlHD","igtvVideoCount", "latestIgtvVideos" , "facebookPage", "relatedProfiles", "likes_"], axis = 1)

In [22]:
fake_data["status"] = 0

In [23]:
full_data = pd.concat([real_data, fake_data])

In [24]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 656 entries, 0 to 343
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   username              656 non-null    object
 1   fullName              644 non-null    object
 2   biography             644 non-null    object
 3   externalUrl           131 non-null    object
 4   followersCount        644 non-null    float64
 5   followsCount          644 non-null    float64
 6   hasChannel            644 non-null    object
 7   highlightReelCount    644 non-null    float64
 8   isBusinessAccount     644 non-null    object
 9   joinedRecently        644 non-null    object
 10  businessCategoryName  65 non-null     object
 11  private               644 non-null    object
 12  verified              644 non-null    object
 13  profilePicUrl         644 non-null    object
 14  postsCount            644 non-null    float64
 15  med_likes             526 non-null    float64
 16  status                656 non-null    int64
dtypes: float64(5), int64(1), object(11)
memory usage: 92.2+ KB

In [25]:
full_data["businessCategoryName"].unique()

array([None, 'Personal Goods & General Merchandise Stores',
       'Creators & Celebrities', 'Lifestyle Services',
       'Food & Personal Goods', 'General Interest', 'Publishers',
       'Business & Utility Services', nan, 'Professional Services'],
      dtype=object)

In [26]:
full_data["externalUrl"] = full_data["externalUrl"].astype(bool)

In [27]:
full_data["externalUrl"].value_counts()

externalUrl
False    513
True     143
Name: count, dtype: int64

In [28]:
full_data["profilePicUrl"] = full_data["profilePicUrl"].astype(bool)
full_data["profilePicUrl"].value_counts()

profilePicUrl
True    656
Name: count, dtype: int64

In [29]:
full_data.head()

,username,fullName,biography,externalUrl,followersCount,followsCount,hasChannel,highlightReelCount,isBusinessAccount,joinedRecently,businessCategoryName,private,verified,profilePicUrl,postsCount,med_likes,status
0,lady__jossy,Amponsah Amponsah Baah,Data Scientist \nWild honey üçØ \nWild flower üå∫ ...,False,772.0,500.0,False,4.0,False,False,None,False,False,True,18.0,47.5,1
1,ama_afrak,Gladys Ama KonaduüáÆüáπüá¨üá≠üá≥üá±üá¨üáß,The Jesus Kind of Girl\nEducationist @gsconsul...,False,1010.0,3020.0,False,8.0,False,False,None,False,False,True,16.0,70.5,1
2,liz.naya,Liz Wilson Amoofia,Kindly follow my Business page @accesorize_gh\...,False,672.0,536.0,False,2.0,False,False,None,False,False,True,463.0,57.5,1
3,12th._street,Gabriel Engmann,Pharm D\nMPSGH\nBeat Producer\nLink up:12thstr...,False,303.0,408.0,False,0.0,False,False,None,False,False,True,4.0,6.5,1
4,nii_mantse__,Nii Tetteh,#KingdomCitizen\nGraphic Designer/Video Editor...,False,913.0,802.0,False,2.0,False,False,None,False,False,True,7.0,143.0,1

In [30]:
full_data.tail(2)

,username,fullName,biography,externalUrl,followersCount,followsCount,hasChannel,highlightReelCount,isBusinessAccount,joinedRecently,businessCategoryName,private,verified,profilePicUrl,postsCount,med_likes,status
342,ninijojo47,,Hi guysüí£üòçüòç\nIm niniüôà,False,63.0,5039.0,False,0.0,False,False,None,False,False,True,4.0,4.0,0
343,sara1112500,sara.1112,,False,71.0,4982.0,False,0.0,False,False,None,False,False,True,26.0,2.5,0

In [31]:
full_data = full_data.sample(frac=1).reset_index(drop=True)

In [32]:
full_data.head(5)

,username,fullName,biography,externalUrl,followersCount,followsCount,hasChannel,highlightReelCount,isBusinessAccount,joinedRecently,businessCategoryName,private,verified,profilePicUrl,postsCount,med_likes,status
0,njfnzhadau,njfnzhadau,,False,85.0,6147.0,False,0.0,False,False,None,False,False,True,10.0,1.0,0
1,mona.babr,,,False,192.0,5867.0,False,0.0,False,False,None,False,False,True,4.0,22.5,0
2,asadosivandf,,,False,145.0,6257.0,False,0.0,True,False,Creators & Celebrities,False,False,True,22.0,2.0,0
3,arezu_0099,,,False,75.0,3693.0,False,0.0,False,False,None,False,False,True,22.0,0.0,0
4,tmtbylayinka,Layinka,Award Winning MUA\nDestination Wedding MUA\nBr...,True,59503.0,1911.0,False,3.0,False,False,None,False,False,True,2853.0,838.5,1

In [33]:
full_data.to_csv("../data-new/full_data.csv")

In [34]:
full_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 656 entries, 0 to 655
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   username              656 non-null    object
 1   fullName              644 non-null    object
 2   biography             644 non-null    object
 3   externalUrl           656 non-null    bool
 4   followersCount        644 non-null    float64
 5   followsCount          644 non-null    float64
 6   hasChannel            644 non-null    object
 7   highlightReelCount    644 non-null    float64
 8   isBusinessAccount     644 non-null    object
 9   joinedRecently        644 non-null    object
 10  businessCategoryName  65 non-null     object
 11  private               644 non-null    object
 12  verified              644 non-null    object
 13  profilePicUrl         656 non-null    bool
 14  postsCount            644 non-null    float64
 15  med_likes             526 non-null    float64
 16  status                656 non-null    int64
dtypes: bool(2), float64(5), int64(1), object(9)
memory usage: 78.3+ KB